# Q-Learning

In this homework, you should complete the Q-learning algorithm for the environment gym taxi

In [1]:
import gym
import numpy as np
import random



## Step 1 Create the environment
Using the API imported from gym

In [2]:
env = gym.make('Taxi-v3')
env.render()

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+



## Step 2  Create the Q-table and initialize it

You can use the gym api to fetch the dimension of action space and state space

In [3]:
action_space = env.action_space
state_space = env.observation_space

# Please complete this initialization in this line
Q_table = np.zeros((state_space.n, action_space.n))

print(Q_table)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


## Step 3 Configure the hyperparameters

In [17]:
total_episodes = 50000
total_test_episodes = 100
learning_rate= 0.7
max_steps = 99

# discount rate
gamma= 0.618

# Create the hyperparameters
sample_rewards = []

## Step 4 Q Learning algorithm

Note: The formula of Q table update(Bellman equation)
    ![Bellman equation](https://raw.githubusercontent.com/hanruihua/NoteBook/master/AI-Note/equation.png)

In [18]:
for episode in range(total_episodes):
    state= env.reset()
    step=0
    done=False
    sample_reward = 0 
    while True:

        action = np.argmax(Q_table[state,:])

        new_state, reward, done, info = env.step(action)
        sample_reward += reward
        Q_table[state, action] = Q_table[state, action] + learning_rate * (reward + gamma * np.max(Q_table[new_state, :]) - Q_table[state, action])
        state = new_state

        if done == True:
            sample_rewards.append(sample_reward)
            break
            

    if episode%1000 == 0:
        mean_reward = np.mean(sample_rewards)
        sample_rewards = []
        print("average reward:" +str(episode)+ ": "+str(mean_reward))

average reward:0: 5.0
average reward:1000: 7.959
average reward:2000: 7.942
average reward:3000: 7.941
average reward:4000: 8.016
average reward:5000: 8.02
average reward:6000: 8.006
average reward:7000: 7.981
average reward:8000: 7.937
average reward:9000: 7.772
average reward:10000: 7.887
average reward:11000: 8.038
average reward:12000: 7.897
average reward:13000: 7.966
average reward:14000: 7.828
average reward:15000: 7.841
average reward:16000: 7.942
average reward:17000: 7.853
average reward:18000: 7.875
average reward:19000: 7.984
average reward:20000: 7.953
average reward:21000: 7.941
average reward:22000: 7.989
average reward:23000: 7.985
average reward:24000: 7.897
average reward:25000: 7.987
average reward:26000: 7.961
average reward:27000: 7.9
average reward:28000: 7.978
average reward:29000: 7.949
average reward:30000: 7.893
average reward:31000: 7.996
average reward:32000: 8.057
average reward:33000: 7.981
average reward:34000: 7.966
average reward:35000: 7.94
average rew

## Step 5 Test your Q table

In [19]:
env.reset()
rewards=[]

for episode in range(total_test_episodes):
    state=env.reset()
    step = 0
    done =False
    total_rewards = 0

    for step in range(max_steps):
        
        action = np.argmax(Q_table[state,:])
        
        new_state, reward, done, info = env.step(action)
        
        total_rewards += reward
        if done:
            rewards.append(total_rewards)
            break
        state = new_state
     
env.close()
print("test:")
print("average reward over 100 episode:"+ str(np.mean(rewards)))

test:
average reward over 100 episode:8.1
